// src/services/RegistryService.ts

// This service handles pushing built Docker images to a remote container registry.
// ASSUMPTION: The user has already authenticated their local Docker CLI with the target registry (e.g., via 'docker login').
import { spawn } from 'child_process';
import { EventEmitter } from 'events';

export class RegistryService {
  /**
   * Pushes a successfully built image to your remote container registry.
   * * @param localTag The tag generated by the ExecutorService (e.g., 'env-zkp-noir:latest')
   * @param registryUrl Your remote registry (e.g., '123456789.dkr.ecr.us-east-1.amazonaws.com')
   */
  public static pushImage(localTag: string, registryUrl: string): EventEmitter {
    const pushStream = new EventEmitter();
    
    // Create the fully qualified remote tag
    const remoteTag = `${registryUrl}/${localTag}`;

    pushStream.emit('data', `Preparing to push image to ${registryUrl}...\n`);

    try {
      // Step 1: Tag the local image for the remote registry
      // 'docker tag local-image remote-registry/local-image'
      const tagProcess = spawn('docker', ['tag', localTag, remoteTag]);

      tagProcess.on('close', (tagCode) => {
        if (tagCode !== 0) {
          return pushStream.emit('error', `Failed to tag image for remote registry. Exit code: ${tagCode}`);
        }

        pushStream.emit('data', `Image tagged successfully. Starting upload...\n`);

        // Step 2: Push the image
        // 'docker push remote-registry/local-image'
        const pushProcess = spawn('docker', ['push', remoteTag]);

        pushProcess.stdout.on('data', (data) => pushStream.emit('data', data.toString()));
        pushProcess.stderr.on('data', (data) => pushStream.emit('data', data.toString()));

        pushProcess.on('close', (pushCode) => {
          if (pushCode === 0) {
            pushStream.emit('success', `\nUpload complete! Image is now available at ${remoteTag}`);
          } else {
            pushStream.emit('error', `\nPush failed with exit code ${pushCode}. Are you authenticated?`);
          }
        });
      });

    } catch (err: any) {
      pushStream.emit('error', `Registry Service Error: ${err.message}`);
    }

    return pushStream;
  }
}