// pipeline/assembler/DockerfileAssembler.ts

/* this module is responsible for taking the structured PipelineManifest and turning it into a Dockerfile string that can be built by Docker.
 * It handles the translation of build steps into RUN commands, the stitching together of stages with COPY --from, and the injection of environment variables and entrypoints.
 * It also maintains an internal context to optimize WORKDIR usage and ensure that commands are run in the correct directories without redundant path changes. */
// pipeline/assembler/DockerfileAssembler.ts

import { PipelineManifest, DockerStage } from '../types/stage';
import { BuildStep } from '../../shared/types/env';
import { PackageManagerRules } from '../../shared/utils/packagemanager_rules'
import { PipelineContext } from '../ContextManager';

export class DockerfileAssembler {
  private manifest: PipelineManifest;
  private context: PipelineContext;

  constructor(manifest: PipelineManifest) {
    this.manifest = manifest;
    this.context = new PipelineContext(manifest.globalEnv, manifest.bootUpAsRoot);
  }

  public assemble(): string {
    let dockerfile = '# syntax=docker/dockerfile:1.4\n'; 
    dockerfile += '# Generated by Cloud IDE Build Pipeline\n\n';

    for (const stage of this.manifest.stages) {
      this.context.setPath('/'); 
      dockerfile += this.buildStage(stage);
      dockerfile += '\n';
    }

    return dockerfile.trim();
  }

  private buildStage(stage: DockerStage): string {
    let out = `FROM ${stage.baseImage} AS ${stage.name}\n\n`;

    const envKeys = Object.keys(stage.envVars);
    if (envKeys.length > 0) {
      out += 'ENV ';
      out += envKeys.map(k => `${k}="${stage.envVars[k]}"`).join(' \\\n    ');
      out += '\n\n';
    }

    if (stage.inboundArtifacts && stage.inboundArtifacts.length > 0) {
      out += '# --- Artifact Transfers ---\n';
      for (const transfer of stage.inboundArtifacts) {
        out += `COPY --from=${transfer.sourceStage} ${transfer.sourcePath} ${transfer.destinationPath}\n`;
      }
      out += '\n';
    }

    if (stage.steps.length > 0) {
      out += '# --- Execution Steps ---\n';
      for (const step of stage.steps) {
        if (step.targetPath && this.context.getPath() !== step.targetPath) {
          out += `WORKDIR ${step.targetPath}\n`;
          this.context.setPath(step.targetPath);
        }
        out += this.translateStep(step);
      }
      out += '\n';
    }

    if (stage.role === 'runtime' && !this.manifest.bootUpAsRoot) {
      out += '# --- Drop Privileges ---\n';
      out += 'USER sandbox-user\n\n';
    }

    if (stage.entrypoint && stage.entrypoint.length > 0) {
      out += `ENTRYPOINT ["${stage.entrypoint.join('", "')}"]\n`;
    }
    if (stage.cmd && stage.cmd.length > 0) {
      out += `CMD ["${stage.cmd.join('", "')}"]\n`;
    }

    return out;
  }

  private translateStep(step: BuildStep): string {
    const rule = PackageManagerRules[step.type];
    if (!rule) throw new Error(`Assembler Error: No rule found for '${step.type}'`);

    // We assume BuildKit is always enabled for this modern pipeline
    const flags = ['--use-buildkit'];
    const rawCommand = rule.getBuildCommand(step, flags);
    const cleanCommand = rawCommand.replace(/^cd\s+\S+\s+&&\s+/, '');

    return `RUN ${cleanCommand}\n`;
  }
}